name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: kumarstack55/setup-git@v1
        with:
          config-scope: '--global'
